name: .NET Core

on: 
  pull_request:
    branches: 
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.202
    
    - name: Build
      run: dotnet build --configuration Release src/LogDNA.sln

    - name: Test
      run: dotnet test --configuration Release --no-build src/UnitTests
